In [40]:
import tkinter as tk
window=tk.Tk()
window.title("TAMBOLA")

import random
import numpy as np
from collections import Counter


ticket=np.zeros((18,9),dtype=int)
total_boxes=[(i,j) for i in range(18) for j in range(9)]
selected_boxes=[]
d=0
t=0
for j in range(10):
    c=[x for x in range(9)]
    for k in range(9):
        t+=1
        if t%5==1:
            d+=1
        rand=random.sample(c,1)
        select=[(d-1,rand[0])]
        selected_boxes+=select
        c.remove(rand[0])
res=[ele for ele,count in Counter(selected_boxes).items() if count>1]
for x in res:
    selected_boxes.remove(x)

for x in res:
    rough1=[i for i in range(18)]
    rough2=[i for i in range(9)]
    rough3=[]
    temp1=x[0]
    temp2=x[1]
    rows=[0 for i in range(18)]
    for y in selected_boxes:
        if y[1]==temp2:
            for j in range(18):
                if y[1]==j:
                    rough1.remove(y[0])
        if y[0]==temp1:
            for i in range(9):
                if y[1]==i:
                    rough2.remove(i)
    r1=rough1[0]
    for y in selected_boxes:
        if y[0]==r1:
            for i in range(9):
                if y[1]==i:
                    rough3.append(i)
    r2=rough1[0]
    sam1=[(r1,temp2)]
    selected_boxes+=sam1
    
    for g in rough3:
        for f in rough2:
            if g==f:
                dog=g
    sam2=[(r1,dog)]
    selected_boxes.remove(sam2[0])
    sam3=[(temp1,dog)]
    selected_boxes+=(sam3)

t1=[]
t2=[i for i in range(18)]

for j in selected_boxes:
    if j[1]==0:
        t1.append(j[0])
    if j[1]==8:
        t2.remove(j[0])     
for j in t1:
    for k in t2:
        if j==k:
            w=j
selected_boxes.remove((w,0))
selected_boxes+=[(w,8)]        

total_numbers=[[] for i in range(9)]
for i in range(9):
    for j in range(10):
        total_numbers[i].append(j+(i*10))
total_numbers[0].remove(0)
total_numbers[8].append(90)

for i in selected_boxes:
    for j in range(9):
        if i[1]==j:
            number=random.choice(total_numbers[j])
            ticket[i]=number
            total_numbers[j].remove(number)
print(ticket)



numbers=[i for i in range(1,91)]
numbers1=[]
for i in range(90):
    num=random.sample(numbers,1)
    numbers1.append(num[0])
    numbers.remove(num[0])


print(numbers1)

royal1=[]
royal2=[]
for i in range(18):
    royal1.append([])
    for k in range(9):
        x=ticket[i][k]
        if x!=0:
            royal1[i].append(x)
    if i%3==2:
        royal=royal1[i]+royal1[i-1]+royal1[i-2]
        royal2.append((royal))


jaldhi=[]
housie=[]
                    
for i in numbers1:
    for j in range(6):
        for k in royal2[j]:
            if i==k:
                royal2[j].remove(i)
                if len(royal2[j])==10:
                    jaldhi.append(j)
                if len(royal2[j])==0:
                    housie.append(j)
print('jaldhi=',jaldhi)
print('housie=',housie)


lower_line=[]
middle_line=[]
upper_line=[]

for i in numbers1:
    for j in range(18):
        for k in royal1[j]:
            if i==k:
                royal1[j].remove(i)
                if len(royal1[j])==0:
                    line=j
                    if line%3==0:
                        upper_line.append(line)
                    if line%3==1:
                        middle_line.append(line)
                    if line%3==2:
                        lower_line.append(line)
print("lower line",lower_line)
print("middle line",middle_line)
print("upper line",upper_line)

display=tk.Label(text='lets play tambola',height='2',width='10')
display.grid(row=7,column=11)


extra=[]
i=0
def run_program():
    global i
    global numbers1
    global ticket
    global extra
    number=numbers1[i]
    extra.append(number)
    
    
    
    
    display=tk.Label(text='present number',height='2',width='10')
    display.grid(row=2,column=13)
    display=tk.Label(text=numbers1[i],height='2',width='10')
    display.grid(row=3,column=13)
    button=[]
    colour=['snow','orange','green','skyblue','pink','yellow']
    c=0
    
    
    
    for j in range(18):
        if j%3==0:
            c+=1
        for k in range(9):
            button.append([])
            integer=(j*(9)+k)
            num=ticket[j][k]
            if num in extra:
                if num==extra[-1]:
                    integer=(j*(9)+k)
                    def display():
                        button[integer]=tk.Button(text=num,height='2',width='2',fg='black')
                        button[integer].configure(bg='red')
                    button[integer]=tk.Button(text=num,height='2',width='2',fg='black',bg=colour[c-1],command=display)
                    button[integer].grid(row=j,column=k,sticky="nsew")
                elif num!=extra[-1]:
                    button[integer]=tk.Button(text=num,height='2',width='2',fg='black',bg='red')
                    button[integer].grid(row=j,column=k,sticky="nsew")
            elif num!=0:
                button[integer]=tk.Button(text=num,height='2',width='2',fg='black',bg=colour[c-1])
                button[integer].grid(row=j,column=k,sticky="nsew")
            elif num==0:
                button[integer]=tk.Button(text='',height='2',width='2',fg='black',bg=colour[c-1])
                button[integer].grid(row=j,column=k,sticky="nsew")
    i+=1
    if i>=2:
        display=tk.Label(text='previous number',height='2',width='10')
        display.grid(row=9,column=13)
        display=tk.Label(text=numbers1[i-2],height='2',width='10')
        display.grid(row=10,column=13)

buton=tk.Button(text="click me",height='2',width='10',command = run_program)
buton.grid(row=7,column=13,sticky="nsew")
window.mainloop()

[[ 4 12  0  0 49  0  0 77 85]
 [ 0 14 26 36  0 53  0 74  0]
 [ 1 11  0 35 47  0 62  0  0]
 [ 9  0 20  0  0 58 67 79  0]
 [ 5 13  0 32  0  0  0 71 87]
 [ 0  0 23 33 43 59 65  0  0]
 [ 0 10 27  0 48  0  0 72 84]
 [ 8 18  0  0  0 56 63  0 82]
 [ 0  0 22 30 42 52  0 73  0]
 [ 0 16 25 37  0 50  0  0 86]
 [ 3  0  0  0 40  0 68 78 80]
 [ 0  0 29  0 41 57 66  0 83]
 [ 0 19  0 38  0  0 61 76 90]
 [ 2  0 24 31 44  0  0  0 89]
 [ 0  0 28 39  0 51 64  0 81]
 [ 0 17  0  0 45 54 60 70  0]
 [ 6  0  0  0 46 55 69 75  0]
 [ 7 15 21 34  0  0  0  0 88]]
[57, 64, 22, 88, 55, 23, 36, 63, 68, 62, 74, 10, 18, 51, 5, 25, 65, 21, 76, 12, 31, 32, 46, 90, 29, 37, 8, 14, 59, 85, 34, 66, 15, 24, 17, 6, 3, 69, 27, 86, 19, 47, 30, 2, 20, 28, 84, 48, 33, 39, 70, 78, 13, 26, 83, 11, 75, 52, 89, 73, 35, 82, 61, 72, 1, 44, 87, 43, 53, 7, 80, 81, 56, 71, 50, 40, 4, 79, 49, 9, 67, 42, 54, 38, 60, 77, 45, 58, 16, 41]
jaldhi= [4, 3, 2, 0, 1, 5]
housie= [2, 4, 0, 5, 1, 3]
lower line [2, 5, 17, 14, 8, 11]
middle line [16, 13,